FROM python:3.11.11-alpine3.20

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app/

EXPOSE 8000

RUN cd /app/twitter_scraper && python manage.py makemigrations
RUN cd /app/twitter_scraper && python manage.py migrate

CMD ["python", "/app/twitter_scraper/manage.py", "runserver", "0.0.0.0:8000"]
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]