# Generated by Django 5.1.4 on 2025-01-08 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_influencer_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='fetched_at',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='username',
        ),
        migrations.AddField(
            model_name='tweet',
            name='influencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='scraper.influencer'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
