# Generated by Django 5.1.4 on 2025-01-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_influencer_tweet_remove_tweet_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
