# Generated by Django 5.1.4 on 2025-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_tweet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='followers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='trend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tweets_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
