# Generated by Django 5.1.4 on 2025-01-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_influencer_category_influencer_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
