# Generated by Django 5.1.4 on 2025-01-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_influencer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='comment',
        ),
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='percentual',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
