# Generated by Django 5.1.4 on 2025-01-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_influencer_id_alter_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
