# Generated by Django 5.1.4 on 2025-01-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_alter_tweet_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='rank',
        ),
    ]
